name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  cd:
    name: Continuous Delivery (Simulado)
    runs-on: ubuntu-latest
    needs: ci  # Garante que CI rode antes da entrega
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload simulated build
        uses: actions/upload-artifact@v4
        with:
          name: meuprojetoCICD
          path: |
            README.md
            Calculadora.js