name: Simulando Continuous Delivery

on:
  push:
    branches: 
        -main
jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: meuprojeto.zip
          path: |
            Calculadora.js
            README.md
  deploy:
    runs-on: ubuntu-latest
    needs: deliver   
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: projetozipado.zip
    - name: Display structure of downloaded files
      run: ls -R